name: DamsotPlugin
version: 1.0
main: com.damsotplugin.DamsotPlugin
api-version: 1.20
commands:
  spawnRazlom:
    description: Спавнить розлом на рандомних координатах
  fracadd:
    description: Додати гравця до фракції
    usage: /fracadd <nickname> <name_fraction>
  fracmenu:
    description: Відкрити меню фракції
    usage: /fracmenu