name: DamsotPlugin
version: 1.0
main: com.damsotplugin.DamsotPlugin
api-version: 1.20
commands:
  spawnRazlom:
    description: Управление разломами.
    usage: /spawnRazlom <RiftName> <open|close>
  fracadd:
    description: Додати гравця до фракції
    usage: /fracadd <nickname> <name_fraction>
  fracmenu:
    description: Відкрити меню фракції
    usage: /fracmenu
  viewteam:
    description: Увидеть всех тиммейтов
    usage: /viewteam
  checkTownyLocation:
    description: Проверить местоположение игрока в Towny